### ISSUE TITLE
Rakudo 2015.05 breaks TOML

### ISSUE THREAD

**Issue by atweiden** [Mouq/toml-pm6#2]
This module is broken after updating to Rakudo 2015.05 from 2015.04. It appears to be inserting a filler `0 => $(Any,)` key pair to `from-toml`'s returned hash based on the TOML source file (posted below).

Could the `[Currencies.BTC.Prices.USD]` section getting overwritten by the section `[Currencies.LTC.Prices.USD]` be yielding the problematic `0 => $(Any,)`?

```
$ PERL6LIB=lib bin/nightscape.pl examples/sample.transactions
[DEBUG] {:USD({"0" => $(Any,), "2014-01-01" => 13.45, "2014-01-02" => 12.34, "2014-01-03" => 11.11, "2014-01-04" => 10.09, "2014-01-05" => 9.08, "2014-01-06" => 8.07, "2014-01-07" => 7.06})}<>
Invalid Date string '0'; use yyyy-mm-dd instead
  in block  at lib/Nightscape/Config.pm:159
  in method gen_pricesheet at lib/Nightscape/Config.pm:152
  in block  at bin/nightscape.pl:182
  in sub MAIN at bin/nightscape.pl:157
  in block <unit> at bin/nightscape.pl:227
  in any <unit-outer> at bin/nightscape.pl:1
```

``` toml
base-currency = "USD"

[Personal]

[Personal.Bankwest.Cheque]
open = "2014-01-01 .. *"

[Personal.Suntrust.Savings]
open = "2024-11-11 .. *"

[Peanut]

[Business]
base-currency = "USD"
open = "2014-01-02 .. *"

[Currencies.BTC.Prices.USD]
"2014-01-01" = 770.4357
"2014-01-02" = 808.0485
"2014-01-03" = 830.024
"2014-01-04" = 858.9833
"2014-01-05" = 940.0972
"2014-01-06" = 951.3865
"2014-01-07" = 810.5833
"2014-11-11" = 999.999

[Currencies.LTC.Prices.USD]
"2014-01-01" = 13.45
"2014-01-02" = 12.34
"2014-01-03" = 11.11
"2014-01-04" = 10.09
"2014-01-05" = 9.08
"2014-01-06" = 8.07
"2014-01-07" = 7.06
```
